### ISSUE TITLE
import data error

### ISSUE THREAD

**Issue by aehyok** [coderabbit214/document-ai#3]
![image](https://user-images.githubusercontent.com/5900140/225251837-b0eb8d2a-4b31-4e09-bafa-61a1aa821508.png)

code position
![image](https://user-images.githubusercontent.com/5900140/225252178-92d42165-2e8b-4c73-adc5-4fadbb124e1a.png)
I am debugging locally。

**Comment by coderabbit214** [comment]
--header 'Content-Type: application/json'

**Comment by aehyok** [comment]
我header里面加了的

**Comment by aehyok** [comment]
![image](https://user-images.githubusercontent.com/5900140/225278308-1a8a4356-5308-4b32-a536-bf606943c09a.png)
数据都有了，没太明白问题出在哪里

**Comment by aehyok** [comment]
![image](https://user-images.githubusercontent.com/5900140/225282263-03c00d41-edb3-4eb1-8dba-7560cd9d3894.png)
gdrant报错了，

**Comment by coderabbit214** [comment]
<img width="1067" alt="截屏2023-03-15 18 50 18" src="https://user-images.githubusercontent.com/61609783/225287421-e56bd5e1-d8a6-4e48-ad6d-f52a4fbec8b2.png">

**Comment by coderabbit214** [comment]
参数是json

**Comment by coderabbit214** [comment]
你也可以选择在命令行直接运行curl

**Comment by aehyok** [comment]
![image](https://user-images.githubusercontent.com/5900140/225291058-5422b2cf-2a6d-422b-8d6c-77f087eb6079.png)
奇怪了

**Comment by aehyok** [comment]
我把qdrant 重新搞了一下好了， 麻烦了大佬

**Comment by xulei324** [comment]
@aehyok 我也遇到这个问题，是咋弄好的啊。云环境 和 本地docker镜像 都有这问题。  
qdrant:
    image: "qdrant/qdrant:v1.1.2"
    ports:
      - "6333:6333"
    volumes:
      - "./qdrant/storage:/qdrant/storage"

**Comment by aehyok** [comment]
@xulei324 找到问题了吗

**Comment by xulei324** [comment]
@aehyok 找到了，自己傻了，没弄懂向量库的机制。
